version: "3.8"

services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./plugins:/app/plugins
      - ./world:/app/world
      - ./eula.txt:/app/eula.txt
    restart: unless-stopped
